basic_banking_system/basic_banking_system/urls.py
from django.contrib import admin
from django.urls import path,include
from transactions import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include('transactions.urls')),
    
]

basic_banking_system/transactions/urls.py
from django.urls import path
from . import views

app_name = 'transactions'

urlpatterns = [
    
    path('',views.home,name = 'home'),
    path('customers',views.customer,name = 'customer'),
    path('transfer',views.transfer,name = 'transfer'),
    path('transop',views.transop,name = 'transop'),
    path('transaction_table',views.transaction_table, name = 'transaction_table'),
]

basic_banking_system/transactions/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length = 256)
    account_number = models.CharField(max_length = 10)
    email = models.EmailField()
    location = models.CharField(max_length = 256)
    balance = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

class Transaction(models.Model):
    debited_from = models.ForeignKey(
        Customer, on_delete=models.CASCADE, related_name="sender")
    credited_to = models.ForeignKey(
        Customer, on_delete=models.CASCADE, related_name="receiver")
    amount = models.IntegerField(default=0)
    transaction_date = models.DateTimeField(auto_now_add=True)
    transaction_status = models.CharField(max_length=255, default="PENDING")




    def get_transaction_by_sender(self, customer_id):
        return Transaction.objects.filter(debited_from=customer_id).order_by('-transaction_date')

    def get_transaction_by_receiver(self, customer_id):
        return Transaction.objects.filter(credited_to=customer_id).order_by('-transaction_date')

basic_banking_system/transactions/views.py
from django.shortcuts import render
from .models import Customer,Transaction

template_name = 'transfer.html'
# Create your views here.
def home(request):
    return render(request,"index.html")

def customer(request):
    custs = Customer.objects.all()

    return render(request,"customers.html",{'data':custs})

def transfer(request):
    
    custs = Customer.objects.all()
    
    return render(request,"transfer.html",{'data':custs})

def transop(request):
    if request.method  == 'POST':
        cred_to = request.POST["transfer_to"]
        debt_from =  request.POST["transfer_from"]
        amount = request.POST["amount"]
        try:
            receiver = Customer.objects.get(account_number= cred_to)
            sender = Customer.objects.get(account_number= debt_from)
            amount = int(amount)
            if amount <= sender.balance:
                
                sender.balance -= amount
                receiver.balance += amount
                sender.save()
                receiver.save()
                new_txn = Transaction(
                    debited_from=sender, credited_to=receiver, amount=amount,  transaction_status="SUCCESS")
                new_txn.save()
                data = Transaction.objects.all().order_by('-transaction_date')
                context={'data':data,'message': "Transaction successful."}        
                return render(request,"transactions.html" , context)
                    
            
            
            else:
                new_txn = Transaction(
                    debited_from=sender, credited_to=receiver, amount=amount,  transaction_status="FAILED")
                new_txn.save()
                custs = Customer.objects.all()
                return render(request, template_name, {'data':custs,'error': "Account doesn't have sufficient balance."})
        except Customer.DoesNotExist:
            return render(request, template_name, {"error": "Account Number does not match with any customer."})

    else:
        return render(request, template_name)


def transaction_table(request):
    data = Transaction.objects.all().order_by('-transaction_date')
    context={'data':data}
    return render(request,"transactions.html",context)

basic_banking_system/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.5/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">



   
    <title>Basic Bank</title>
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand">TSF </h3>
          <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link" href="{% url 'transactions:home' %}">HOME</a>
            <a class="nav-link" href="{% url 'transactions:customer' %}">CUSTOMERS</a>
            <a class="nav-link" href="{% url 'transactions:transaction_table' %}">TRANSACTIONS</a>
            <link rel="preconnect" href="https://fonts.gstatic.com">
            <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
          </nav>
        </div>
      </header>
  {% block body_block %}

  {% endblock %}
      <footer id="footer" class="mastfoot mt-auto">
        <div class="inner">
          <p>© 2021-2022 <EM>TSF- Kaushal Singh</EM>. All Rights Reserved.</p>
        </div>
      </footer>
      </section>
    </div>
</html>

basic_banking_system/templates/customers.html
{% extends "base.html" %}

{% block body_block %}

    <h1>Customers:</h1>
    <table class="table table-striped table-dark">
        <thead>
          <tr>
            
            <th style="  white-space:nowrap;" >NAME</th>
            <th style="  white-space:nowrap;" >ACCOUNT NO</th>
            <th style="  white-space:nowrap;" >EMAIL</th>
            <th style="  white-space:nowrap;" >LOCATION</th>
            <th style="  white-space:nowrap;" >BALANCE</th>
            
          </tr>
        </thead>
        <tbody>
          
          {% for customers in data %}
          <tr>
            <td style=" white-space:nowrap">{{customers.name}}</td>
            <td style=" white-space:nowrap">{{customers.account_number}}</td>
            <td style=" white-space:nowrap">{{customers.email}}</td>
            <td style=" white-space:nowrap">{{customers.location}}</td>
            <td style=" white-space:nowrap">{{customers.balance}}</td>
          </tr>
          {% endfor %}
          
          
        </tbody>
      </table>


{% endblock %}

basic_banking_system/templates/index.html
{% extends "base.html" %}
{% load static %}
  {% block body_block %}
      <main role="main" class="inner cover">
        <h1 class="cover-heading">BASIC&nbsp;BANKING&nbsp; SYSTEM</h1>
        <section id="sec">
          <div id="x" class="container ">
            <p class="lead" style="font-family: 'Staatliches', cursive ">It is the simple dynamic website which can tranfer money from one user to another . As per the Task given by The Sparks Foundation.
              Created by <em> Kaushal Singh</em><br> So lets started !
            </p>
          </div>
          <p>
  
            <a href="{% url 'transactions:transfer' %}" class="btn btn-lg btn-secondary">TRANSFER MONEY</a>
          </p class="lead">
  
      </main>
  {% endblock %}

basic_banking_system/templates/transactions.html
{% extends "base.html" %} 

{% load static %}

{% block body_block %}

<h1>Transactions History:</h1>
<table class="table table-striped table-dark">
    <thead>
      <tr>
        
        <div class = "w-50 p-1"><th style=" width :46%" >TRANSFERED FROM</th></div>
        <div class = "w-50 p-1"><th style=" width :46%" >TRANSFERED TO</th></div>
        <div class = "w-50 p-1"><th style=" width :46%" >AMOUNT</th></div>
        <div class = "w-50 p-1"><th style=" width :46%" >TRANSACTION STATUS</th></div>
        <!-- <th scope="col">TRANSACTION DATE</th> -->
      </tr>
    </thead>
    <tbody>
      
      {% for trans in data %}
      <tr>
        
        <td scope="col">{{trans.debited_from}}</td>
        <td scope="col">{{trans.credited_to}}</td>
        <td scope="col">{{trans.amount}}</td>
        <td scope="col">{{trans.transaction_status}}</td>
        <!-- <th scope="col">{{trans.transaction_date}}</th> -->
        
       
      </tr>
      {% endfor %}
      
      
    </tbody>
  </table>

{% endblock %}

basic_banking_system/templates/transfer.html
{% extends "base.html" %}

{% block body_block %}



    <h1>Banking System</h1>
    <form action="transop" method = "POST"  >
      {% csrf_token %}
      <div class="form-group row">
        <label  class="col-sm-2 col-form-label">Transfer From:</label>
        <div class="col-lg-10">
      <select class="form-control form-control-lg" aria-label="Default select example" name = "transfer_from">

        <div class="col-lg-20">
        <option selected>Transfer From </option>

        {% for customers in data %}
        <option value={{customers.account_number}}>{{customers.name}},Account NO: {{customers.account_number}}</option>
        {% endfor %}
        
      </select>
    </div>
  </div>


        <div class="form-group row">
          <label  class="col-sm-2 col-form-label">Transfer To:</label>
          <div class="col-lg-10">
        <select class="form-control form-control-lg" aria-label="Default select example" name = "transfer_to">

          <div class="col-lg-20">
          <option selected>Transfer To </option>

          {% for customers in data %}
          <option value={{customers.account_number}}>{{customers.name}} , Account NO: {{customers.account_number}}</option>
          {% endfor %}
          
        </select>
      </div>
    </div>


        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-2 col-form-label">Amount:</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="amount" placeholder="">
            </div>
          </div>
        
        <p>
        <div class="form-group row">
          <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div></p>
      </form>

      {% if error is not null %}
      <div class="alert alert-dark" role="alert">
        {{error}}
        
      </div>
      {% endif %}
      


{% endblock %}